#! /bin/sh

rm codec.c
touch codec.c

echo 'int lastMovesSize=lastMoves.size(); int arch1,arch2; if (lastMovesSize>1) {arch1=lastMoves[1];} if (lastMovesSize>2) {arch2=lastMoves[2];}' >> codec.c

#=========Ping-Chiang recommandations after games held on March 9 Taipei 2011

./sequenceConverter F3 D7 C5 E5 >> codec.c
./sequenceConverter E5 E7 F3 E3 E4 D3 C4 C7 F7 F2 G3 F8 F6 C3 B5 G2 >> codec.c
./sequenceConverter E5 E7 E6 D7 F7 E3 F8 D4 C5 F4 G5 D5 D6 C6 B6 C7 C4 B7 C3 G4 H5 D2 C2 H4 >> codec.c
./sequenceConverter F5 D5 D6 C6 D7 E5 F6 F4 >> codec.c
./sequenceConverter F5 D5 E3 E7 F7 E6 F6 E4 F3 D3 D2 C2 >> codec.c
./sequenceConverter F5 D5 D4 C4 E4 C3 D6 C5 E6 H5 C6 E2 F2 E3 F3 G4 F4 G7 >> codec.c
./sequenceConverter F3 D7 C5 F6 >> codec.c
./sequenceConverter E4 E6 C5 F5 F4 C6 >> codec.c
./sequenceConverter E4 E6 C5 F5 F4 C6 B6 >> codec.c
./sequenceConverter E5 E7 D7 E3 E8 F7 >> codec.c
./sequenceConverter F6 D4 E4 E3 D5 C5 E5 F3 >> codec.c
./sequenceConverter F6 D4 E4 E3 D5 C5 E5 C6 >> codec.c
./sequenceConverter E5 E7 D3 E3 E4 F3 F7 D4 C4 F6 E6 D2 D5 G7 F8 G6 >> codec.c
./sequenceConverter E5 E7 G6 D3 C4 F3 C3 C7 H3 G4 H4G5 H5 F6 >> codec.c
./sequenceConverter E5 E7 C6 F3 D3 G5 >> codec.c
./sequenceConverter E5 E7 C6 F3 D3 E4 >> codec.c
./sequenceConverter F3 D7 C5 F6 >> codec.c
./sequenceConverter F4 D6 C7 D7 C6 D5 C5 D4 >> codec.c
./sequenceConverter F4 D6 C7 C6 D7 E6 E7 F6 >> codec.c

#===========Below Sequence was provided by Ping-Chang Chou 02192011============

# If black do not play E5, then let mogo play  Symmetrical points. provided by Ping-Chang Chou 02192011

./sequenceConverter F5 D5 >> codec.c
./sequenceConverter F6 D4 >> codec.c
./sequenceConverter F7 D3 >> codec.c
./sequenceConverter G7 C3 >> codec.c
./sequenceConverter G5 C5 >> codec.c
./sequenceConverter H7 D5 >> codec.c
./sequenceConverter H6 D5 >> codec.c

#White Rule.  Merge all Franch and Taiwan white open book, by  Ping-Chang Chou 02192011

./sequenceConverter E5 E7 F7 E3 D3 F8 G7 D4 E4 C3 D2 F3 C4 D5 E6 B4 C5 D6 B3 C6 C2 G5 E8 D7 D8 C8 >> codec.c
./sequenceConverter E5 E7 F7 E3 D3 F8 F6 D4 E4 C3 D2 C2 D5 C4 F3 G8 E2 B6  >> codec.c
./sequenceConverter E5 E7 E3 C6 F7 F6 E6 G7 F8 G8 F5 G6 D7 E8 D8 F9 D6 C3 C5 B5 B6 C4 C7 D2 >> codec.c
./sequenceConverter E5 E3 C5 F7 F4 D7 F3 C3 B6 F2 G2 D2 H7 G7 F1 E2 B4 B3 H6 B8 G8 F8 H8 B7 D4 B2 D6 E7 G6 F6 F5 E1 G1 G9 H9 F9 A3 A2 A4 A6 A5 A7 C4 C7 C6 D3 E6 E4 >> codec.c
./sequenceConverter E5 E3 G5 D7 C5 G7 E7 E8 D6 C7  >> codec.c
./sequenceConverter E5 E3 G5 D7 C5 G7 C7 D6 D5 C3 G3 F6 F5 F2 B2 B3 C8 E8 D2 D3 C2 A2 G2 E2 E6 H8 B4 H6 F8 F7 F1 E1 E7 D8  >> codec.c
./sequenceConverter E5 E3 F3 E7 C5 F4 F5 F2 G8 C7 B6 F8 G7 B7 D8 E8  >> codec.c
./sequenceConverter E5 E3 C5 F7 G6 C7 G4 C3 G7 F8 >> codec.c
./sequenceConverter E5 E3 C5 F7 G5 C7 D7 D6 D5 D8  >> codec.c
./sequenceConverter E5 E7 D7 E3 E6 F7 G4 D8 C3 G6 G3 D6 C7 C6 C8 B6 E8 F8 D9 D4 >> codec.c
./sequenceConverter E5 E7 D7 E3 E6 F7 G4 D8 C3 G6 G3 D6 C7 C6 B7 D4 D5 C4 C5 B3 F2 B5 B6 E2 H5 H6 C8 E8 J6 J7 J5 H8 A5 B4 E1 D1 F1 C2  >> codec.c
./sequenceConverter E5 E7 D7 E3 E6 F7 G6 G3 D3 D8 E4 C7 E2 F6 F5 G5 G4 H5 H4 H6 D6 C6 C8 E8 C5 B5 B4 C4 D5 F3 F4 J4 J3 J5 H3 B6 B3 B8 A5 A6  >> codec.c
./sequenceConverter E5 E7 D7 E3 E6 F7 G6 G3 D3 D8 E4 C7 F3 G7 H5 E2 F2 C3 D2 C5 D6 C6 H7 H8 J8 C2 G8 F8 H9 C1 C4 B4 D4 D1 E1 F6 F5 F9 G9 C8  >> codec.c
./sequenceConverter E5 E7 G5 D3 C5 G3 F7 F8 G7 C7 C3 E3 D8 E8 C8 C6  >> codec.c
./sequenceConverter E5 E7 D7 E3 F7 E6 D6 F6 F5 G6 G5 E8 H6 H7 C3 D5 D4 C5 C6 B5 B6 D8 B4 G3  >> codec.c
./sequenceConverter E5 E7 G6 D3 C4 F3  >> codec.c
./sequenceConverter E5 D3 C4 G4 F4 G6 F3 C5 C6 B5 D5 B6 G3 F7 E8 H4 E7 D4 G8 H8 H9 G7 H7 F8 F9 G9 C3 E9 C2 C7  >> codec.c
./sequenceConverter E5 C5 D6 G5 G4 F4 F5 G3 H4 G6 H3 F3 G2 F2 H2 F7 D3 C3  >> codec.c
./sequenceConverter E5 C5 C6 G5 G4 B6 C7 F4 F5 G3 H4 G6 F3 E4 D5 D4 C4 F2 B5 F7 H3 E3 G2 G1 H2 D2 >> codec.c
./sequenceConverter E5 C6 C4 E7 G5 F4 F5 E3 D3 G4 E4 E2  >> codec.c
./sequenceConverter E5 E3 F4 F3 G3 E7 D6 C3  >> codec.c
./sequenceConverter E5 E3 D4 D3 G5 D7 C3 G3 E8 E7 F7 D8 F8 C6 C2 H4 H2 G2 F1 D2 D1 G1 E1 J2 J3 H1 J1 H5 H6 J2 B5 B6 J1 C5 C4 J2 A4 B8 J1 G6 F6 J2 >> codec.c
./sequenceConverter E5 E3 C4 F7 F6 G3 G7 E7 C7 G8 H6 D6 E4 C6 D8 B7 B8 D7 C8 B6 E8 F8 A8 B9  >> codec.c
./sequenceConverter E5 E7 C5 F3 G5 C3 E3 E2 F4 C7 F2 D2 B6 G3 G2 G7 H7 B7 D6 H3 H2 B4 D7 H8 F8 H6 H5 E8 D8 B5 G6 J7 C6 A6 B8 A8 C8 D4 E4 B2 F7 G8 E9 F1 J5 J6 H1 A7 G9 H9  >> codec.c
./sequenceConverter E5 E7 F6 C4 D4 C3 C5 B5 D3 F7 C6 B6 G7 G8 C7 H7 G6 H6 H5 G5 G4 J5 H4 E6 F5 D8 D2 B7 C8 C2  >> codec.c
./sequenceConverter E5 E7 F6 C4 D4 C3 C5 B5 C6 D3 F3 G7 F7 F8 G6 H8 H7 G8 B6 E2 F2 E4 E3 D5 D6 D4 E8 F4 H5 H4 B4 B3 G4 G3 G5 D8 D7 H3 E9 A4 J4 G2 A6 J3 J5 F5 A5 B4  >> codec.c
./sequenceConverter E5 E3 F3 G7 G6 F7 D7  >> codec.c
./sequenceConverter F6 D4 F3 D6  >> codec.c
./sequenceConverter G6 D4 D6 F4 G4 F6 F3 G5 H5 F5 H3 G7 E3 D5  >> codec.c
#Black Rule.  Merge all Franch and Taiwan black open book, by  Ping-Chang Chou 02192011

./sequenceConverter F6 D4 E4 E6 E5 D5 D6 E7 C6  >> codec.c
./sequenceConverter E5 E7 G6 D3 C4 F3 >> codec.c
./sequenceConverter E5 C4 D3 G6 F7 D6 G4  >> codec.c
./sequenceConverter E5 C6 C4 E7 G5 F4 F5 E3 D3 G4 E4 >> codec.c
./sequenceConverter E5 F3 G4 G3 D3 C5 D5 C6 D7 C7 H4 C4 E3 D8 E8 E7 F7 D6 F8 C3 C2 B2 D2 E6 F6 B1 D9 C9 E9 C1 D1 D4 E4  >> codec.c
./sequenceConverter E5 G4 F3 G3 G6 E7 E6 C7 F7 C5 F2 G2 F4 E2 F1 E8 F8 D4 D7 D8 D6 C6 C8 B8 E9 C9 D2 C2 D1 C1 E1 E3 D5 C3 E4 D9 F9 >> codec.c
./sequenceConverter E5 E3 F3 G7 F4 C4 C6 E7 C3 D3 C2  >> codec.c

