#!/bin/csh -f

# this mogo:
# 9x9
# 5 minutes per side
# 4 threads
# ==> ok for cgos

echo Launching mogo on tipi44 for cgos 9x9

cd CGOS9x9
../cgos3.9x9.tcl MoGo mogomogo 'ssh -X tipi44 ../../mogo --9 --totalTime 300 --nbThreads 4 --pondering 1 --playsAgainstHuman 0' gracefully_exit_server

