#!/bin/csh -f

# this mogo:
# 9x9
# 28 minutes per side
# 4 threads
# ==> ok for kgs

TODO the port is unknown for the moment --- ../mogo --19 --totalTime 1680 --nbThreads 4 --pondering 1 --playsAgainstHuman 0

