#!/bin/sh

/home/orsay/hdoghmen/FUSEKI_BLACK11/srcFUSEKI/mogoSEVEN --9 --pathsFuseki "/home/orsay/hdoghmen/FUSEKI_BLACK11/SGFSFUSEKI-7-8.5-12H_BLACK/" --nbThreads 8 --earlyCut 1080 --time 1080 --timeManagementMode 1 --pondering 0 

