#ifndef GE_PARAM_MANAGER_MOVES_H
#define GE_PARAM_MANAGER_MOVES_H

#define GE_BONUS_NO_BORDER 1
#define GE_BONUS_NO_CORNER 1
#define GE_BONUS_STAT_MOVES 100
#define GE_BONUS_STAT_DISTANCE 100
#define GE_BONUS_TERRITORIES 1

#endif
